### ISSUE TITLE
Outdated version v1.0.1 in Ansible galaxy

### ISSUE THREAD

**Issue by rriski** [cimon-io/ansible-role-asdf#21]
Hi,

Would you be able to import the latest changes to galaxy https://galaxy.ansible.com/cimon-io/asdf, the current version fails at "/home/$USER/.asdf/plugins/nodejs/bin/import-release-team-keyring" step which has been fixed by the latest commit https://github.com/cimon-io/ansible-role-asdf/commit/51a42a80f329b570958615007e55c61802fed82f.

Thanks

**Comment by konradrr** [comment]
+1

@rriski Thanks for creating this issue. I ran into the same problem. Fortunately, don't have to debug it anymore :)

**Comment by merifri** [comment]
Hi. Done.

Please mention me if something happens :-)
