### ISSUE TITLE
Support for other shells (zsh, ...)

### ISSUE THREAD

**Issue by makkus** [cimon-io/ansible-role-asdf#9]
Quick question: is there a reason for:

    [ -n "$BASH_VERSION" ] || return 0

in the init file? This prevents loading of asdf when zsh is used. According to: https://github.com/asdf-vm/asdf/blob/master/README.md#setup zsh at least would also work when sourcing the ``asdf.sh`` file.

Might be neat to also support fish, seeing as asdf supports that too...

Should only be minor changes, but happy to send a pull request if you want.

**Comment by merifri** [comment]
Yes, there is a reason.
- "classic" Bourne shell has no `source` command.
- ZSH does not read `/etc/profile` file by default.

So such a trick will not work:
```
[ -n "$BASH_VERSION" -o -n "$ZSH_VERSION" ]
```

I can add support for zsh/fish, but as a separate tasks. And I think it will look something like this:

- check if zsh is installed for the current user (or /etc/zprofile.d (?) exists)
- if exists, upload the script to this directory.

Maybe you can offer a better solution?

**Comment by makkus** [comment]
Interesting, I wasn't aware of any of this.

In that case, I think you were right and it doesn't make too much sense to deal with that in this role. I reckon I can just add it to a $HOME/.profile or $HOME/.zshrc using an extra task, in cases where it's necessary. Thanks!

**Comment by nullvariable** [comment]
In case anyone lands here from search or looking for a solution for this, I use this role: https://github.com/gantsign/ansible-role-oh-my-zsh

To add the asdf plugin for zsh, which does autocomplete and all that jazz, works well in conjunction with this role
